### ISSUE TITLE
AnalyzerResults GenerateFrameTabularText() specified channel

### ISSUE THREAD

**Issue by DarkPatrick** [saleae/AnalyzerSDK#12]
Hi.

i'm trying to implement multichannel protocol and i've stuck into one problem.
Is there any way to find out current channel in AnalyzerResults::GenerateFrameTabularText() method just like it is already implemented in AnalyzerResults::GenerateBubbleText()?

Best regards, Egor.

**Comment by Marcus10110** [comment]
Hi Egor,

Sorry for the very late reply to this.

GenerateBubbleText gets called once per frame, not once per frame & channel like it does for the bubble text version.

You are allowed to add as many rows as you like for each frame too, so if one row isn't sufficient to hold data from all channels, you can just add more output lines.

All output lines you add get displayed in the list, unlike the get bubble text function, which only displays the longest string that could fit on the display.
