### ISSUE TITLE
gdb on linux doesn't seem to work with logic 2.3

### ISSUE THREAD

**Issue by andrasbiro** [saleae/AnalyzerSDK#24]
I can easily debug my custom analyzer with logic 1.2.18, but when I change the gdb binary to 2.3, it just doesn't work, vs code claims my cpp file is not loaded yet.

This is especially annoying because my analyzer causes logic 2.3 to crash, but not 1.2.

And BTW, for a couple of years you are "working' to get windows debug available with up to date versions....

I checked high level analyzers, it does not seem to work for me in its current state. I would need Async serial AND an extra signal

(this is a copy of https://github.com/saleae/SampleAnalyzer/issues/15 )

**Comment by Marcus10110** [comment]
I've responded on the SampleAnalyzer issue, because that's where our debugging instructions live. I'll close this copy.
