### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by arianAsg** [saleae/AnalyzerSDK#30]
HI, I have question in connection with UI of software, i want to change the UI and add some button to it. is there any possibility for it?

**Comment by timreyes** [comment]
@arianAsg We don't have a way to modify the behavior of the UI of our software. Our Analyzer SDK is specifically used to create new custom low level analyzers that could be used to add support for decoding protocols that are not immediately supported by our software.

Some examples of custom analyzers that other users have created using our Analyzer SDK and shared with the public can be found below:
https://support.saleae.com/community/community-shared-protocols

I'll go ahead and close this GitHub issue, however, in case you'd like to post an official request for allowing the ability to change UI elements in our software, feel free to get that posted on our ideas site below!
https://ideas.saleae.com/b/feature-requests/
