### ISSUE TITLE
snprintf MSVC define

### ISSUE THREAD

**Issue by martonmiklos** [saleae/AnalyzerSDK#7]
At the end of the LogicPublicTypes.h file there is the following code is present:
`#ifdef _MSC_VER
#define snprintf _snprintf_s
#define vsnprintf vsprintf_s
#endif`

This breaks the "cross compilation" of my analyzers between Linux and MSVC because the snprintf has the following prototype:

`int snprintf ( char * s, size_t n, const char * format, ... );`

While the _snprintf_s has the following:
`int _snprintf_s(  
   char *buffer,  
   size_t sizeOfBuffer,  
   size_t count,  
   const char *format [,  
   argument] ...   
);  `

Is it a typo or is it intended?

**Comment by martonmiklos** [comment]
@Marcus10110  any comments on this one?

**Comment by Marcus10110** [comment]
Sorry for not looking into this before.
That's been in the software for a long time, so I assumed it did something useful. However after checking, it doesn't look like `snprintf` is used anywhere in our codebases. Very odd.
I'll get this removed.

**Comment by martonmiklos** [comment]
Hi Mark,

Yeah the problems came up when you try to use ```snprintf``` in a 3rd party analyzer and you try to compile it on Windows with MSVC. If you get this removed I can get rid of the following code piece in my analyzers :D :

```#ifdef _MSC_VER
// HACK ALERT!!
// see https://github.com/saleae/AnalyzerSDK/issues/7
#undef snprintf
#define snprintf _snprintf
#endif```

**Comment by Marcus10110** [comment]
Fixed with https://github.com/saleae/AnalyzerSDK/commit/08ae41c089e2a1ea2b6eba0ad637739407e5d8bc
Let me know if you have any trouble with it!
